GET http://localhost:3000/shipments/S00001197

###

GET http://localhost:3000/organizations/34f195b5-2aa1-4914-85ab-f8849f9b541a
###

GET http://localhost:3000/transport-packs/total-weight?unit=ounces